apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
        - name: weather
          image: ortalnosik/my-weather-service
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "weatherdb"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5000

            env:
- name: DB_CONNECTION_STRING
  value: "Driver={ODBC Driver 17 for SQL Server};Server=tcp:WeatherSQLServer.database.windows.net,1433;Database=WeatherDB;Uid=sqladmin;Pwd=Ortal123!;Encrypt=yes;TrustServerCertificate=no;Connection Timeout=30;"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  selector:
    app: weather
